source "http://api.berkshelf.com"

cookbook 'base', path: 'tulp_repo/cookbooks/base'
cookbook 'postgresql', path: 'tulp_repo/cookbooks/postgresql'
cookbook 'redis', path: 'tulp_repo/cookbooks/redis'
cookbook 's3backup', path: 'tulp_repo/cookbooks/s3backup'
cookbook 'user', path: 'tulp_repo/cookbooks/user'
cookbook 'tulp', path: 'tulp_repo/cookbooks/tulp'
cookbook 'zabbix', path: 'tulp_repo/cookbooks/zabbix'
cookbook 'crontab', path: 'tulp_repo/cookbooks/crontab'
cookbook 'riemann', path: 'chef-riemann'
cookbook 'tulp-riemann', path: 'chef-tulp-riemann'
cookbook 'tulp-sales', path: 'tulp-sales'
cookbook 'apt'
cookbook 'git'
cookbook 'nginx'
cookbook 'lvm'
cookbook 'java'
cookbook 'ntp'
cookbook 'iptables'
cookbook 'sysctl'
cookbook 'timezone'
cookbook 'postfix'
cookbook 'locales'
cookbook 'rvm', github: 'fnichol/chef-rvm'
cookbook 'rbenv', github: 'tulp/rbenv-cookbook'
cookbook 'emacs24', git: 'git@github.com:Sliim/emacs24-chef-cookbook.git'
